FROM dunglas/frankenphp:php8.4-bookworm

WORKDIR /var/www/html

RUN install-php-extensions \
	gd \
	intl \
	zip \
	opcache

RUN apt update -y && apt install -y jq

COPY --chown=www-data:www-data . .
COPY ./docker/symfony.prod.ini /usr/local/etc/php/conf.d/symfony.prod.ini
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

EXPOSE 80
EXPOSE 443
EXPOSE 2019